config/routes.rb
Rails.application.routes.draw do

  resources :sessions
  resources :users
  resources :events
  resources :joins
  resources :messages

  get 'session/log_out' => 'sessions#log_out'
  post 'sessions/sign_in' => 'sessions#sign_in'
  delete 'delete' => 'joins#destroy'

end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :user
  has_many :joins, dependent: :destroy
  has_many :messages, dependent: :destroy
  validates :name, :city, :state, :user_id, presence: true
  # validates :date, date: { after: Proc.new { Time.now } }
end

app/models/join.rb
class Join < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :user_id, :event_id, presence: true
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  belongs_to :event
  validates :content, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :events, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :joins, dependent: :destroy
  validates :first_name, :last_name, :city, :state, presence: true
  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]+)\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: EMAIL_REGEX }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    User.find(session[:user_id]) if session[:user_id]
  end
  
  helper_method :current_user

  def require_login
    redirect_to new_session_path if session[:user_id] == nil
  end


  def destroy
    secret = Secret.find(params[:id])
    secret.destroy if secret.user == current_user
    redirect_to "/users/#{current_user.id}"
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
  	@us_states = us_states
  	@user = User.find(session[:user_id])
  	@events = Event.all
  	@users = User.all
  	@joins = Join.all
  end

  def show
  	@event = Event.find(params[:id])
  	@host = User.where(id: @event.user_id).first.first_name
  	@joins = Join.where(event_id: params[:id])
  	@users = User.all
    @messages = @event.messages
  end

  def create
  	@event = Event.create(name: params[:name], date: params[:date], city: params[:city], state: params[:state], user_id: session[:user_id])
  	if @event
  		redirect_to events_path
  	else
  		flash[:add_event_errors] = @event.errors.full_messages
  		redirect_to events_path
  	end
  end

  def us_states
	["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
  end
end

app/controllers/joins_controller.rb
class JoinsController < ApplicationController
	def update
		Join.create(user_id: session[:user_id], event_id: params[:id])
		redirect_to events_path
	end

	def destroy
		Join.where({user_id: params[:user_id], event_id: params[:event_id]}).first.destroy
		redirect_to events_path
	end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	def create
		Message.create(content: params[:content], user_id: session[:user_id], event_id: params[:event_id])
		redirect_to event_path(params[:event_id])
	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :require_login, except: [:new, :create]
  def new
  	@us_states = us_states
  end

  def sign_in
    @user = User.find_by(email: params[:email]).try(:authenticate, params[:password])
    if @user
        session[:user_id] = @user.id
        session[:log_in] = true
        session[:state] = @user.state
        redirect_to events_path
    else
        flash[:errors] = "Invalid email/password combination"
        # session[:errors] = "Invalid email/password combination"
        redirect_to new_session_path
    end
  end

  def log_out
    # session[:log_in] = false
    # session[:user_id] = nil
    reset_session
    redirect_to new_session_path
  end

  def us_states
   ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit
    @user = User.find(params[:id])
    @us_states = us_states
  end

  def create
    @user = User.create(first_name: params[:first_name], last_name: params[:last_name], email: params[:email], city: params[:city], state: params[:state], password: params[:password], password_confirmation: params[:password_confirmation])
    if @user.id
        session[:user_id] = @user.id
        session[:log_in] = true
        session[:state] = @user.state
        redirect_to events_path
    else
        flash[:errors] = @user.errors.full_messages
        redirect_to new_session_path
    end
  end

  def update
    # fail
    user = User.find(params[:id])
    user.first_name = params[:first_name]
    user.last_name = params[:last_name]
    user.email = params[:email]
    user.city = params[:city]
    user.state = params[:state]
    user.save
    # user.update(first_name: params[:frist_name], last_name: params[:last_name], email: params[:email], city: params[:city], state: params[:state])
    session[:state] = user.state
    redirect_to events_path
  end

  def us_states
    ["AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FL", "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", "OR", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VA", "WA", "WV", "WI", "WY"]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<%= link_to "Edit Profile", edit_user_path(session[:user_id]) %>
<h1>Welcome, <%= @user.first_name%></h1>

<h3>Here are some of events at your state:</h3>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Location</th>
			<th>Host</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<% @events.each do |event|%>
		<% if event.state == session[:state] %>
		<tr>
			<td><a href="/events/<%= event.id%>"><%= event.name %></a></td>
			<td><%= event.date%></td>
			<td><%= event.city%></td>
			<td><%= @users.where(id: event.user_id).first.first_name %></td>
			<td>
				<% if event.user_id != session[:user_id]%>
					<% if @joins.where(event_id: event.id) && event.joins.where(user_id: session[:user_id]).any? %>
						Joining <%= button_to "Cancel", { :controller => :joins, :action => "destroy", :event_id => event.id, :user_id => session[:user_id] }, :method => "delete"%>
					<% else %>
						<%= button_to "Join", {:controller => :joins, :action => "update", :id => event.id}, :method => :patch %>
					<% end%>
				<% end%>
			</td>
		</tr>
		<% end%>
	<% end%>
	</tbody>
</table>

<h3>Here are some of events on other states:</h3>
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Date</th>
			<th>Location</th>
			<th>State</th>
			<th>Host</th>
			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<% @events.each do |event|%>
		<% if event.state != session[:state] %>
		<tr>
			<td><a href="/events/<%= event.id%>"><%= event.name %></a></td>
			<td><%= event.date%></td>
			<td><%= event.city%></td>
			<td><%= event.state%></td>
			<td><%= @users.where(id: event.user_id).first.first_name %></td>
			<td>
				<% if event.user_id != session[:user_id]%>
					<% if @joins.where(event_id: event.id) && event.joins.where(user_id: session[:user_id]).any? %>
						Joining <%= button_to "Cancel", { :controller => :joins, :action => "destroy", :event_id => event.id, :user_id => session[:user_id] }, :method => "delete"%>
					<% else %>
						<%= button_to "Join", {:controller => :joins, :action => "update", :id => event.id}, :method => :patch %>
					<% end%>
				<% end%>
			</td>
		</tr>
		<% end%>
	<% end%>
	</tbody>
</table>

<h2>Add Event</h2>
<form action='/events' method='post'>
 	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<label for='name'>Name: </label>
	<input type='text' id='name', name='name'>
	<label for='date'>Date: </label>
	<input type='date', id='date', name='date'>
	<label>Location: </label>
	<input type='text' name='city'>
	<select name='state'>
	<% @us_states.each do |state| %>
		<option><%= state %></option>
	<% end %>
	</select>
	<button type='submit'>Add Event</button>
</form>

app/views/events/show.html.erb
<%= link_to "Events Dashboard", events_path %>
<h1><%= @event.name%></h1>
<h2>Host: <%= @host%></h2>
<h2>Date: <%= @event.date%></h2>
<h2>Location: <%= @event.city%>, <%= @event.state%></h2>
<p>People who joining the event: <%=@joins.count%></p>
<table>
	<thead>
		<tr>
			<td>Name:</td>
			<td>Location:</td>
			<td>State:</td>
		</tr>
	</thead>
	<tbody>
	<% @joins.each do |join|%>
		<tr>
			<td><%=@users.find(join.user_id).first_name%> <%= @users.find(join.user_id).last_name%></td>
			<td><%=@users.find(join.user_id).city%></td>
			<td><%=@users.find(join.user_id).state%></td>
		</tr>
	<% end%>	
	</tbody>
</table>

<div style="width: 700px; height: 200px; overflow: scroll; border: 1px solid gray; padding: 10px">
	<% @messages.each do |message|%>
	<p><%= @users.find(message.user_id).first_name%>: <%= message.content%></p>
	<% end%>
</div>
<h3>Add Comments:</h3>
<form action='/messages' method='post'>
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<input type='hidden' name='event_id' value="<%=@event.id%>">
	<textarea name='content'></textarea>
	<button>Submit Comments</button>
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Black Belt Reviewer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
    <p><%= flash[:errors] %></p>
<% end %>
<% if current_user %>
  <%= button_to "Log Out", session_log_out_path, method: :get %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/edit.html.erb
<%= link_to "Events Dashboard", events_path %>

<h2>Edit Your Profile</h2>
<form class="form-horizontal" action="/users/<%= @user.id%>" method='post'>
	<input name="authenticity_token" value="<%= form_authenticity_token %>" type="hidden">
	<input type='hidden' name='_method' value='patch'>
  	<div class="form-group">
    	<label for="first_name" class="col-sm-2 control-label">First Name: </label>
	   	<div class="col-sm-10">
	   		<input type="text" class="form-control" id="first_name" name='first_name' value="<%= @user.first_name %>">
	   	</div>
	</div>

  	<div class="form-group">
    	<label for="last_name" class="col-sm-2 control-label">Last Name: </label>
	   	<div class="col-sm-10">
	   		<input type="text" class="form-control" id="last_name" name='last_name' value="<%= @user.last_name%>">
	   	</div>
	</div>

  	<div class="form-group">
    	<label for="inputEmail3" class="col-sm-2 control-label">Email: </label>
	   	<div class="col-sm-10">
	   		<input type="email" class="form-control" id="inputEmail3" name='email' value="<%= @user.email %>">
	   	</div>
	</div>

	<div class="form-group">
    	<label class="col-sm-2 control-label">Location: </label>
	   	<div class="col-sm-10">
	   		<input type="text" class="form-control" name='city' value="<%= @user.city%>">
	   		<select name='state'>
	   		<% @us_states.each do |state| %>
	   			<option><%= state %></option>
	   		<% end %>
	   		</select>
	   	</div>
	</div>


	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
				<button type="submit" class="btn btn-default">Update</button>
		</div>
	</div>
</form>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>